baseURL = 'https://warguide.hackerschool.io/'
languageCode = 'en-us'
title = 'Guia do Workshop de Android do Recrutamento'
theme="anubis"

[params]
style="auto"

    [[params.social]]
        id = "github"
        name = "filipe-varela"